### ISSUE TITLE
Re-run pipeline for 'ci:' commits?

### ISSUE THREAD

**Issue by MortenLohne** [stacc/github-workflow-actions#18]
If following the [Angular Convention](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines) for conventional commits, the `ci:` commit message prefix is used for changes to CI. After such a commit, you usually want to run your pipeline again, but that only happens after a new release is created via a `feat:` or `fix:` prefix. Is it possible to re-run a publish pipeline for `ci:` commits somehow?

Potential solutions:
* Create a new minor version on `ci:` commits, like with `fix:`.
* Re-run the publish pipeline with the same version number. Risks overriding a previous release
* Avoid the problem, and limit commits to be either `feat:` or `fix:`?

**Comment by AuStien** [comment]
It varies how big a change to the CI is. Keeping it so that `ci:` doesn't bump version makes it possible to choose how to bump the change.

Some changes warrants no change; `ci:`, some changes warrants patch; `fix(ci):`, some changes warrants minor; `feat(ci):` and some changes could warrant major; `[type](ci)!:` or `BREAKING CHANGE: [explanation]` in footer of commit message.

It's a bit inconvenient to have changes on the same code scoped as either *type* or *scope*, but I think it's a fine solution.

**Comment by XSlemX** [comment]
I agree with @AuStien here. We can certainly allow type `ci` to bump minor, but there is certainly enough wiggle room with his proposal just using `ci` as the scope.

Our current pipelines rely on triggers and re-running `version` would not create a new release, hence not running workflow with `release-trigger`. Re-running the build workflows would reproduce artifact(s) and potentially(and most likely) fail when pushing. 

Also, I've been using the `build` type where I should`ve used `ci` 🙈

**Comment by XSlemX** [comment]
Closing this as it went stale and agreement(?)
